server:
  port: 5000
spring:
  sql.init.mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_PLATFORM} #org.hibernate.dialect.PostgreSQLDialect 
    defer-datasource-initialization: true
  datasource:
    #platform: postgres # might change to postgresql # !ENV ${DATASOURCE_PLATFORM}
    url: ${DB_URL} #jdbc:postgresql://db-service.p3-space.svc.cluster.local:5432/postgres?user=postgres&password=example

    driver-class-name: ${DB_DRIVER} #org.postgresql.Driver 
    username: postgres
    password: example
    initialization-mode: always

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: p3applicationmail777@gmail.com
    password: rbi5p8qEqZWTXiQ
    port: '587'

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: "health,prometheus,info"