controller:
  jenkinsUriPrefix: /jenkins
  ingress:
    enabled: true
    apiVersion: "extensions/v1"
    path: /jenkins
    annotations:
      # ingressClassName: nginx
      kubernetes.io/ingress.class: nginx
  additionalPlugins:
  - github:1.34.5
  agent:
    namespace: jenkins
