---
- name: Variables playbook
  hosts: client
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: download repo
      git:
        repo: https://github.com/2206-devops-batch/BryonS-project0.git
        dest: ~/BryonS-project0
        version: master
